{
 "title": "Fraud Detection",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Rule Updates",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rule_updates_total{type=\"rule_updates\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue processing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Gets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "cache_gets_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}